//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Payment.ParsianGatewayReverse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientReversalRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    [System.SerializableAttribute()]
    public partial class ClientReversalRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAccountField;
        
        private long TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount {
            get {
                return this.LoginAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAccountField, value) != true)) {
                    this.LoginAccountField = value;
                    this.RaisePropertyChanged("LoginAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataViewModelBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shopping.Payment.ParsianGatewayReverse.ClientReversalResponseData))]
    public partial class ResponseDataViewModelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientReversalResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    [System.SerializableAttribute()]
    public partial class ClientReversalResponseData : Shopping.Payment.ParsianGatewayReverse.ResponseDataViewModelBase {
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService", ConfigurationName="ParsianGatewayReverse.ReversalServiceSoap")]
    public interface ReversalServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService/ReversalRequest", ReplyAction="*")]
        Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponse ReversalRequest(Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService/ReversalRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponse> ReversalRequestAsync(Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversalRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversalRequest", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService", Order=0)]
        public Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequestBody Body;
        
        public ReversalRequestRequest() {
        }
        
        public ReversalRequestRequest(Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    public partial class ReversalRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Shopping.Payment.ParsianGatewayReverse.ClientReversalRequestData requestData;
        
        public ReversalRequestRequestBody() {
        }
        
        public ReversalRequestRequestBody(Shopping.Payment.ParsianGatewayReverse.ClientReversalRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversalRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversalRequestResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService", Order=0)]
        public Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponseBody Body;
        
        public ReversalRequestResponse() {
        }
        
        public ReversalRequestResponse(Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    public partial class ReversalRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Shopping.Payment.ParsianGatewayReverse.ClientReversalResponseData ReversalRequestResult;
        
        public ReversalRequestResponseBody() {
        }
        
        public ReversalRequestResponseBody(Shopping.Payment.ParsianGatewayReverse.ClientReversalResponseData ReversalRequestResult) {
            this.ReversalRequestResult = ReversalRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReversalServiceSoapChannel : Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReversalServiceSoapClient : System.ServiceModel.ClientBase<Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap>, Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap {
        
        public ReversalServiceSoapClient() {
        }
        
        public ReversalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReversalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReversalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReversalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponse Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap.ReversalRequest(Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest request) {
            return base.Channel.ReversalRequest(request);
        }
        
        public Shopping.Payment.ParsianGatewayReverse.ClientReversalResponseData ReversalRequest(Shopping.Payment.ParsianGatewayReverse.ClientReversalRequestData requestData) {
            Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest inValue = new Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest();
            inValue.Body = new Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequestBody();
            inValue.Body.requestData = requestData;
            Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponse retVal = ((Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap)(this)).ReversalRequest(inValue);
            return retVal.Body.ReversalRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponse> Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap.ReversalRequestAsync(Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest request) {
            return base.Channel.ReversalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Shopping.Payment.ParsianGatewayReverse.ReversalRequestResponse> ReversalRequestAsync(Shopping.Payment.ParsianGatewayReverse.ClientReversalRequestData requestData) {
            Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest inValue = new Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequest();
            inValue.Body = new Shopping.Payment.ParsianGatewayReverse.ReversalRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((Shopping.Payment.ParsianGatewayReverse.ReversalServiceSoap)(this)).ReversalRequestAsync(inValue);
        }
    }
}
